// <auto-generated>
//   Generated by tools/component-packets/generate_seam_catalog.py from the
//   creator-safe rows in quest-capability-manifest.json. Do not edit.
// </auto-generated>

namespace ComfyNetworkSense;

using System;
using System.Collections.Generic;

/// <summary>Stable quest event names shared by the shipping mod and Quest Lab.</summary>
public static class QuestEventCatalog {
  public const string Schema = "comfy-quest-event/v1";

  public readonly struct Definition {
    public string Name { get; }
    public string Category { get; }
    public string Profile { get; }

    public Definition(string name, string category, string profile) {
      Name = name;
      Category = category;
      Profile = profile;
    }
  }

  static readonly Dictionary<string, Definition> _events =
      new Dictionary<string, Definition>(StringComparer.OrdinalIgnoreCase) {
    { "attack_blocked", new Definition("attack_blocked", "combat", "core") },
    { "character_healed", new Definition("character_healed", "combat", "core") },
    { "character_staggered", new Definition("character_staggered", "combat", "core") },
    { "chat_sent", new Definition("chat_sent", "social", "core") },
    { "container_emptied", new Definition("container_emptied", "inventory", "core") },
    { "damage_dealt", new Definition("damage_dealt", "combat", "extended") },
    { "global_key_removed", new Definition("global_key_removed", "world", "core") },
    { "global_key_set", new Definition("global_key_set", "world", "core") },
    { "item_consumed", new Definition("item_consumed", "inventory", "core") },
    { "item_crafted", new Definition("item_crafted", "crafting", "core") },
    { "item_dropped", new Definition("item_dropped", "inventory", "core") },
    { "item_equipped", new Definition("item_equipped", "inventory", "core") },
    { "item_picked_up", new Definition("item_picked_up", "inventory", "core") },
    { "item_unequipped", new Definition("item_unequipped", "inventory", "core") },
    { "kill", new Definition("kill", "combat", "core") },
    { "max_health_changed", new Definition("max_health_changed", "progression", "extended") },
    { "piece_damaged", new Definition("piece_damaged", "building", "extended") },
    { "piece_destroyed", new Definition("piece_destroyed", "building", "core") },
    { "piece_placed", new Definition("piece_placed", "building", "core") },
    { "piece_removed", new Definition("piece_removed", "building", "core") },
    { "piece_repaired", new Definition("piece_repaired", "building", "core") },
    { "player_died", new Definition("player_died", "progression", "core") },
    { "player_teleported", new Definition("player_teleported", "world", "core") },
    { "resource_damaged", new Definition("resource_damaged", "harvest", "extended") },
    { "resource_picked", new Definition("resource_picked", "harvest", "core") },
    { "sign_written", new Definition("sign_written", "social", "core") },
    { "skill_raised", new Definition("skill_raised", "progression", "core") },
    { "skills_lowered", new Definition("skills_lowered", "progression", "core") },
    { "stamina_gained", new Definition("stamina_gained", "progression", "extended") },
    { "stamina_spent", new Definition("stamina_spent", "progression", "extended") },
    { "station_fuel_added", new Definition("station_fuel_added", "crafting", "core") },
    { "station_input_added", new Definition("station_input_added", "crafting", "core") },
    { "station_output_collected", new Definition("station_output_collected", "crafting", "core") },
    { "station_output_produced", new Definition("station_output_produced", "crafting", "core") },
  };

  static readonly Dictionary<string, string[]> _triggerAliases =
      new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase) {
    { "hit", new[] { "damage_dealt", "resource_damaged" } },
  };

  public static int Count { get { return _events.Count; } }
  public static int AliasCount { get { return _triggerAliases.Count; } }
  public static IEnumerable<string> AllEventNames { get { return _events.Keys; } }

  public static bool IsBindable(string eventName) {
    return !string.IsNullOrWhiteSpace(eventName)
        && (_events.ContainsKey(eventName) || _triggerAliases.ContainsKey(eventName));
  }

  /// <summary>Returns the catalog spelling, or null for an unsupported event.</summary>
  public static string CanonicalName(string eventName) {
    Definition definition;
    return !string.IsNullOrWhiteSpace(eventName) && _events.TryGetValue(eventName, out definition)
        ? definition.Name
        : null;
  }

  /// <summary>Whether a schema trigger name accepts this canonical runtime event.</summary>
  public static bool TriggerMatches(string triggerName, string canonicalEventName) {
    if (string.IsNullOrWhiteSpace(triggerName)
        || string.IsNullOrWhiteSpace(canonicalEventName)) {
      return false;
    }
    if (_events.ContainsKey(triggerName)) {
      return string.Equals(triggerName, canonicalEventName, StringComparison.OrdinalIgnoreCase);
    }
    string[] targets;
    if (!_triggerAliases.TryGetValue(triggerName, out targets)) {
      return false;
    }
    foreach (string target in targets) {
      if (string.Equals(target, canonicalEventName, StringComparison.OrdinalIgnoreCase)) {
        return true;
      }
    }
    return false;
  }

  public static bool TryGet(string eventName, out Definition definition) {
    if (string.IsNullOrWhiteSpace(eventName)) {
      definition = default(Definition);
      return false;
    }
    return _events.TryGetValue(eventName, out definition);
  }
}
