namespace ComfyNetworkSense.Tests;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using Newtonsoft.Json;
using ComfyQuestContracts;
using Xunit;

public sealed class ExperienceContractTests {
  const string Valid = """{"schema":"comfy-quest-experience/v1","id":"hello","entry_stage":"start","stages":[{"id":"start","transitions":[{"id":"done","priority":1,"when":{"op":"EVENT","event":"kill","target":"Troll"},"actions":[{"id":"say","type":"message","text":"Skal!"}],"outcome":"complete"}]}],"bindings":[{"id":"sign","experience_id":"hello"}]}""";
  [Fact] public void CompilesMinimalExperience(){var c=ExperienceCompiler.CompileJson(Valid,new HashSet<string>{"kill"});Assert.True(c.IsValid,string.Join(";",c.Diagnostics));}
  [Fact] public void RejectsCycles(){var json=Valid.Replace("\"outcome\":\"complete\"","\"next_stage\":\"start\"");Assert.Contains(ExperienceCompiler.CompileJson(json,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="graph.cycle");}
  [Fact] public void EvaluatesSequenceDeterministically(){var x=new TriggerExpression{Op="SEQUENCE",Children=new(){new(){Op="EVENT",Event="hit"},new(){Op="EVENT",Event="kill"}}};var h=new[]{new RuntimeEvent{Name="hit",At=DateTimeOffset.UnixEpoch},new RuntimeEvent{Name="kill",At=DateTimeOffset.UnixEpoch.AddSeconds(1)}};Assert.True(TriggerEvaluator.Matches(x,h));Assert.False(TriggerEvaluator.Matches(x,new[]{h[1],h[0]}));}
  [Fact] public void RejectsUnknownActions(){Assert.Contains(ExperienceCompiler.CompileJson(Valid.Replace("message","shell"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="action.unsupported");}
  [Fact] public void RejectsUnboundedOrUnknownActionParameters(){var excessive=Valid.Replace("\"text\":\"Skal!\"","\"text\":\"Skal!\",\"command\":\"nocost\"");Assert.Contains(ExperienceCompiler.CompileJson(excessive,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="action.parameter_unknown");var spawn=Valid.Replace("{\"id\":\"say\",\"type\":\"message\",\"text\":\"Skal!\"}","{\"id\":\"say\",\"type\":\"spawn\",\"kind\":\"creature\",\"prefab\":\"Greydwarf\",\"count\":17,\"radius\":30}");Assert.Contains(ExperienceCompiler.CompileJson(spawn,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="action.parameter");}
  [Fact] public void ExperienceAndLegacyCatalogsStayIdentical(){Assert.Equal(new HashSet<string>(QuestEventCatalog.AllEventNames,StringComparer.OrdinalIgnoreCase),new HashSet<string>(CanonicalEventCatalog.All,StringComparer.OrdinalIgnoreCase));}
  [Fact] public void ActivatesOnlyOnExplicitLoad(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"hello.questpack"),"1.0.0",Valid);var store=new QuestPackStore(root);Assert.False(File.Exists(Path.Combine(root,"active","active-set.json")));Assert.Single(store.CheckInbox(new HashSet<string>{"kill"}));var loaded=store.LoadLatest(new HashSet<string>{"kill"});Assert.Equal("1.0.0",loaded.Manifest.Version);Assert.True(File.Exists(Path.Combine(root,"active","active-set.json")));}finally{Directory.Delete(root,true);}}
  [Fact] public void SameVersionDifferentContentFailsClosed(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"a.questpack"),"1.0.0",Valid);WritePack(Path.Combine(inbox,"b.questpack"),"1.0.0",Valid.Replace("Skal!","Hail!"));var store=new QuestPackStore(root);Assert.Throws<InvalidOperationException>(()=>store.LoadLatest(new HashSet<string>{"kill"}));}finally{Directory.Delete(root,true);}}
  [Fact] public void RejectsUnsupportedArchiveEntries(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;var path=Path.Combine(inbox,"unsafe.questpack");WritePack(path,"1.0.0",Valid);using(var zip=ZipFile.Open(path,ZipArchiveMode.Update))using(var writer=new StreamWriter(zip.CreateEntry("scripts/run.txt").Open()))writer.Write("no");Assert.Contains(new QuestPackStore(root).Inspect(path,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="pack.path");}finally{Directory.Delete(root,true);}}
  [Fact] public void SelectsVersionAndRollsBackAtomically(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;WritePack(Path.Combine(inbox,"one.questpack"),"1.0.0",Valid);WritePack(Path.Combine(inbox,"two.questpack"),"2.0.0",Valid.Replace("Skal!","Hail!"));var store=new QuestPackStore(root);Assert.Equal("2.0.0",store.LoadLatest(new HashSet<string>{"kill"}).Manifest.Version);Assert.Equal("1.0.0",store.LoadVersion("demo","1.0.0",new HashSet<string>{"kill"}).Manifest.Version);Assert.Equal("2.0.0",store.Rollback(new HashSet<string>{"kill"}).Manifest.Version);var active=JsonConvert.DeserializeObject<ActiveSet>(File.ReadAllText(Path.Combine(root,"active","active-set.json")));Assert.Equal("2.0.0",active.Version);Assert.False(File.Exists(Path.Combine(root,"active","active-set.json.tmp")));}finally{Directory.Delete(root,true);}}
  [Fact] public void RollbackFailsClosedWhenPreviousPackageChanged(){var root=Path.Combine(Path.GetTempPath(),"comfy-pack-"+Guid.NewGuid().ToString("N"));try{var inbox=Directory.CreateDirectory(Path.Combine(root,"inbox")).FullName;var one=Path.Combine(inbox,"one.questpack");WritePack(one,"1.0.0",Valid);WritePack(Path.Combine(inbox,"two.questpack"),"2.0.0",Valid.Replace("Skal!","Hail!"));var store=new QuestPackStore(root);store.LoadVersion("demo","1.0.0",new HashSet<string>{"kill"});store.LoadLatest(new HashSet<string>{"kill"});File.AppendAllText(one,"tamper");Assert.Throws<InvalidOperationException>(()=>store.Rollback(new HashSet<string>{"kill"}));}finally{Directory.Delete(root,true);}}
  [Fact] public void RuntimeReceiptsAreImmutableFiles(){var root=Path.Combine(Path.GetTempPath(),"comfy-receipt-"+Guid.NewGuid().ToString("N"));try{var store=new RuntimeReceiptStore(root);var path=store.Write(new RuntimeReceipt{Operation="check",Status="accepted",CandidateCount=1,ValidCount=1});Assert.True(File.Exists(path));Assert.Single(store.List());Assert.Empty(Directory.GetFiles(Path.Combine(root,"receipts"),"*.tmp"));Assert.Contains("comfy-quest-runtime-receipt/v1",File.ReadAllText(path));}finally{Directory.Delete(root,true);}}
  [Theory][InlineData(CharmTargetKind.PlayerBuiltPiece)][InlineData(CharmTargetKind.Sign)][InlineData(CharmTargetKind.ItemStand)][InlineData(CharmTargetKind.DedicatedCharm)] public void PrivateHostCanInscribeAllowlistedOwnedTargets(CharmTargetKind kind){var world=new WorldAuthority{IsPrivateWorld=true,IsListenHost=true};Assert.True(CharmPolicy.CanInscribe(world,new CharmTarget{Kind=kind,HasZdo=true,LocallyOwned=true}).Allowed);}
  [Theory][InlineData(CharmTargetKind.Creature)][InlineData(CharmTargetKind.Portal)][InlineData(CharmTargetKind.Terrain)][InlineData(CharmTargetKind.Container)][InlineData(CharmTargetKind.DroppedItem)] public void UnsafeCharmTargetsFailClosed(CharmTargetKind kind){var world=new WorldAuthority{IsPrivateWorld=true,IsSolo=true};Assert.Equal("charm_target_not_allowlisted",CharmPolicy.CanInscribe(world,new CharmTarget{Kind=kind,HasZdo=true,LocallyOwned=true}).Diagnostic);}
  [Fact] public void PeerMutationFailsClosedButReferenceRemainsInspectable(){var world=new WorldAuthority{IsPrivateWorld=true,IsPeerClient=true};Assert.Equal("mutation_authority_unavailable",CharmPolicy.CanMutate(world).Diagnostic);Assert.True(CharmPolicy.ValidateReference(new CharmReference{PackId="demo",ExperienceId="quest",BindingId="default",Version="1.0.0",ContentHash=new string('a',64)}).Allowed);}
  [Fact] public void OmenLiveFixtureIsCertifiedAndHashExact(){var root=Path.Combine(AppContext.BaseDirectory,"LiveTest");var experience=File.ReadAllText(Path.Combine(root,"experiences","omen-inscription.json"));Assert.True(ExperienceCompiler.CompileJson(experience,CanonicalEventCatalog.CreateSet()).IsValid);var bytes=File.ReadAllBytes(Path.Combine(root,"experiences","omen-inscription.json"));var hash=QuestPackContent.ComputeHash(new[]{new KeyValuePair<string,byte[]>("experiences/omen-inscription.json",bytes)});var manifest=JsonConvert.DeserializeObject<QuestPackManifest>(File.ReadAllText(Path.Combine(root,"manifest.json")));Assert.Equal(manifest.ContentHash,hash);}
  [Fact] public void ActionClaimsSurviveDuplicatesAndReload(){var root=Path.Combine(Path.GetTempPath(),"comfy-actions-"+Guid.NewGuid().ToString("N"));try{var key="world|player|zdo|hash|stage|transition|action";Assert.True(new ActionExecutionLedger(root).TryClaim(key));Assert.False(new ActionExecutionLedger(root).TryClaim(key));Assert.True(new ActionExecutionLedger(root).TryClaim(key+"-2"));}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowPersistsPendingTransitionAndAdvancesAfterCompletion(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();var id=new WorkflowIdentity{WorldId="world",CharacterId="hero",BindingZdo="1:2",ContentHash=new string('a',64)};var first=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow});Assert.Equal("first-hit",first.Transition.Id);Assert.False(first.IsPendingReplay);var replay=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow.AddSeconds(1)});Assert.True(replay.IsPendingReplay);Assert.True(new WorkflowStateStore(root).Complete(replay));Assert.Equal("second",new WorkflowStateStore(root).Get(id).StageId);var finish=new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow.AddSeconds(2)});Assert.Equal("finish",finish.Transition.Id);Assert.True(new WorkflowStateStore(root).Complete(finish));Assert.Equal("complete",new WorkflowStateStore(root).Get(id).Outcome);Assert.Null(new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow.AddSeconds(3)}));}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowUsesPriorityThenStableId(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();doc.Stages[0].Transitions.Add(new ExperienceTransition{Id="alternate",Priority=1,When=new TriggerExpression{Op="EVENT",Event="piece_damaged"},Outcome="fail"});var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};Assert.Equal("first-hit",new WorkflowStateStore(root).Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow}).Transition.Id);}finally{Directory.Delete(root,true);}}
  [Fact] public void WorkflowAccumulatesBoundedCountAcrossEvents(){var root=Path.Combine(Path.GetTempPath(),"comfy-workflow-"+Guid.NewGuid().ToString("N"));try{var doc=TwoStage();doc.Stages[0].Transitions[0].When=new TriggerExpression{Op="COUNT",Count=2,Children=new(){new(){Op="EVENT",Event="piece_damaged"}}};var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};var store=new WorkflowStateStore(root);Assert.Null(store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow}));Assert.Equal("first-hit",store.Begin(id,doc,new RuntimeEvent{Name="piece_damaged",At=DateTimeOffset.UtcNow.AddSeconds(1)}).Transition.Id);}finally{Directory.Delete(root,true);}}
  [Fact] public void DurableTimersSurviveReloadUntilAcknowledged(){var root=Path.Combine(Path.GetTempPath(),"comfy-timer-"+Guid.NewGuid().ToString("N"));try{var id=new WorkflowIdentity{WorldId="w",CharacterId="p",BindingZdo="z",ContentHash="h"};var now=DateTimeOffset.UtcNow;new DurableTimerStore(root).Start(id,"bell",now.AddSeconds(2));Assert.Empty(new DurableTimerStore(root).Due(now));var due=Assert.Single(new DurableTimerStore(root).Due(now.AddSeconds(3)));Assert.Equal("bell",due.TimerId);Assert.Single(new DurableTimerStore(root).Due(now.AddSeconds(4)));Assert.True(new DurableTimerStore(root).Acknowledge(due.Key));Assert.Empty(new DurableTimerStore(root).Due(now.AddSeconds(5)));}finally{Directory.Delete(root,true);}}
  [Fact] public void EngineTimerSignalRequiresStableTimerClause(){var valid=Valid.Replace("\"event\":\"kill\",\"target\":\"Troll\"","\"event\":\"timer_elapsed\",\"where\":{\"timer_id\":\"bell\"}");Assert.True(ExperienceCompiler.CompileJson(valid,new HashSet<string>{"kill"}).IsValid);var invalid=valid.Replace("\"where\":{\"timer_id\":\"bell\"}","\"where\":{}");Assert.Contains(ExperienceCompiler.CompileJson(invalid,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="timer.id");}
  [Fact] public void BindingTargetKindsUseClosedRegistry(){var valid=Valid.Replace("\"experience_id\":\"hello\"","\"experience_id\":\"hello\",\"target_kinds\":[\"sign\"]");Assert.True(ExperienceCompiler.CompileJson(valid,new HashSet<string>{"kill"}).IsValid);var invalid=valid.Replace("\"sign\"","\"portal\"");Assert.Contains(ExperienceCompiler.CompileJson(invalid,new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="binding.target_kind");}
  [Fact] public void MutationActionsUseClosedPrefabAndQuantityRegistry(){var grant=Valid.Replace("{\"id\":\"say\",\"type\":\"message\",\"text\":\"Skal!\"}","{\"id\":\"say\",\"type\":\"grant_item\",\"item\":\"Wood\",\"quantity\":50}");Assert.True(ExperienceCompiler.CompileJson(grant,new HashSet<string>{"kill"}).IsValid);Assert.Contains(ExperienceCompiler.CompileJson(grant.Replace("\"Wood\"","\"SwordCheat\""),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="grant_item_not_allowlisted");Assert.Contains(ExperienceCompiler.CompileJson(grant.Replace(":50",":51"),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="grant_quantity_exceeds_stack_cap");var spawn=Valid.Replace("{\"id\":\"say\",\"type\":\"message\",\"text\":\"Skal!\"}","{\"id\":\"say\",\"type\":\"spawn\",\"kind\":\"creature\",\"prefab\":\"Greyling\",\"count\":1,\"radius\":3}");Assert.True(ExperienceCompiler.CompileJson(spawn,new HashSet<string>{"kill"}).IsValid);Assert.Contains(ExperienceCompiler.CompileJson(spawn.Replace("\"Greyling\"","\"Troll\""),new HashSet<string>{"kill"}).Diagnostics,x=>x.Code=="spawn_prefab_not_allowlisted");}
  [Fact] public void SpawnLedgerPersistsExactZdoIdentityAndRemovesOnlySelectedRecords(){var root=Path.Combine(Path.GetTempPath(),"comfy-spawn-"+Guid.NewGuid().ToString("N"));try{var store=new SpawnExecutionStore(root);store.Record(new SpawnedObject{ActionKey="owner|stage-one|transition|spawn",ContentHash="h",ActionId="spawn",UserId=7,ObjectId=9});store.Record(new SpawnedObject{ActionKey="other|stage|transition|spawn",ContentHash="h",ActionId="spawn",UserId=7,ObjectId=10});var one=Assert.Single(new SpawnExecutionStore(root).ForOwnerAction("owner","spawn"));Assert.Equal((uint)9,one.ObjectId);new SpawnExecutionStore(root).Remove(new[]{one});Assert.Empty(new SpawnExecutionStore(root).ForOwnerAction("owner","spawn"));Assert.Single(new SpawnExecutionStore(root).ForOwnerAction("other","spawn"));}finally{Directory.Delete(root,true);}}
  static ExperienceDocument TwoStage()=>new(){EntryStage="first",Stages=new(){new(){Id="first",Transitions=new(){new(){Id="first-hit",Priority=10,When=new(){Op="EVENT",Event="piece_damaged"},NextStage="second"}}},new(){Id="second",Transitions=new(){new(){Id="finish",Priority=10,When=new(){Op="EVENT",Event="piece_damaged"},Outcome="complete"}}}}};
  static void WritePack(string path,string version,string experience){using var zip=ZipFile.Open(path,ZipArchiveMode.Create);using(var writer=new StreamWriter(zip.CreateEntry("manifest.json").Open()))writer.Write($"{{\"schema\":\"comfy-quest-pack/v2\",\"pack_id\":\"demo\",\"version\":\"{version}\"}}");using(var writer=new StreamWriter(zip.CreateEntry("experiences/demo.json").Open()))writer.Write(experience);}
}
